apiVersion: v1
kind: Service
metadata:
  name: web-server
  labels:
    name: web-server
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8888
    targetPort: 8888
  selector:
    app: web-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - image: "wonderflow/gva-server:v1"
          imagePullPolicy: IfNotPresent
          name: gva-server-v1
          ports:
            - containerPort: 8888
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8888
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: config-volume
              mountPath: /gva/config.yaml
              subPath: config.yaml
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: configfile


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configfile
data:
  config.yaml: |
    casbin:
      model-path: './resource/rbac_model.conf'
    jwt:
      signing-key: 'qmPlus'
    mysql:
      username: root
      password: 'Aa@6447985'
      path: mysql.default.svc.cluster.local:3306
      db-name: 'qmPlus'
      config: 'charset=utf8&parseTime=True&loc=Local'
      max-idle-conns: 10
      max-open-conns: 10
      log-mode: true  
    sqlite:
      path: db.db
      log-mode: true
      config: 'loc=Asia/Shanghai'    
    redis:
      addr: redis.default.svc.cluster.local:6379
      password: ''
      db: 0    
    system:
      use-multipoint: true
      env: 'public'  # Change to "develop" to skip authentication for development mode
      addr: 8888
      db-type: "mysql"  # support mysql/sqlite  
    captcha:
      key-long: 6
      img-width: 240
      img-height: 80
    log:
      prefix: '[GIN-VUE-ADMIN]'
      log-file: true
      stdout: 'DEBUG'
      file: 'DEBUG'